
import "./styles/globals.css";
import { Montserrat } from "next/font/google";


export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight >>> https://fonts.google.com/variablefonts
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

const RootLayout = ({children}) => {
  return(
    <html lang="en">
      <body>
        <div className="main">
          <div className="main">
            <div className="gradient"/>
          </div>
          <main className="app">
           {children}
          </main>
        </div>
      </body>
    </html>
  )
}
export default RootLayout;